INSERT INTO Category VALUES (700, "Asian", "Cuisine");
INSERT INTO Category VALUES (701, "Thai", "Cuisine");
INSERT INTO Category VALUES (702, "Vietnamese", "Cuisine");
INSERT INTO Category VALUES (703, "Indian", "Cuisine");
INSERT INTO Category VALUES (704, "Middle Eastern", "Cuisine");
INSERT INTO Category VALUES (705, "Japanese", "Cuisine");
INSERT INTO Category VALUES (706, "Mexican", "Cuisine");
INSERT INTO Category VALUES (707, "Pakistani", "Cuisine");
INSERT INTO Category VALUES (708, "Canadian", "Cuisine");
INSERT INTO Category VALUES (709, "Chinese", "Cuisine");
INSERT INTO Category VALUES (710, "Hawaiian", "Cuisine");
INSERT INTO Category VALUES (711, "Korean", "Cuisine");
INSERT INTO Category VALUES (712, "Greek", "Cuisine");
INSERT INTO Category VALUES (713, "British", "Cuisine");
INSERT INTO Category VALUES (714, "Taiwanese", "Cuisine");
INSERT INTO Category VALUES (715, "Caribbean", "Cuisine");
INSERT INTO Category VALUES (716, "Turkish", "Cuisine");
INSERT INTO Category VALUES (717, "Italian", "Cuisine");
INSERT INTO Category VALUES (718, "Lebanese", "Cuisine");
INSERT INTO Category VALUES (719, "Afghan", "Cuisine");
INSERT INTO Category VALUES (720, "Mediterranean", "Cuisine");
INSERT INTO Category VALUES (721, "French", "Cuisine");
INSERT INTO Category VALUES (722, "Modern European", "Cuisine");
INSERT INTO Category VALUES (723, "Czech", "Cuisine");
INSERT INTO Category VALUES (724, "German", "Cuisine");
INSERT INTO Category VALUES (725, "Persian", "Cuisine");
INSERT INTO Category VALUES (726, "Spanish", "Cuisine");
INSERT INTO Category VALUES (727, "Portuguese", "Cuisine");
INSERT INTO Category VALUES (728, "Ethiopian", "Cuisine");
INSERT INTO Category VALUES (729, "African", "Cuisine");
INSERT INTO Category VALUES (730, "American", "Cuisine");

INSERT INTO Category VALUES (731, "Chicken", "Dishes");
INSERT INTO Category VALUES (732, "Poutineries", "Dishes");
INSERT INTO Category VALUES (733, "Burgers", "Dishes");
INSERT INTO Category VALUES (734, "Sandwiches", "Dishes");
INSERT INTO Category VALUES (735, "Coffee", "Drinks");
INSERT INTO Category VALUES (736, "Sushi", "Dishes");
INSERT INTO Category VALUES (737, "Salads", "Dishes");
INSERT INTO Category VALUES (738, "Pizza", "Dishes");
INSERT INTO Category VALUES (739, "Hot Dogs", "Dishes");
INSERT INTO Category VALUES (740, "Juice Bar", "Drinks");
INSERT INTO Category VALUES (741, "Wraps", "Dishes");
INSERT INTO Category VALUES (742, "Ice Cream", "Dishes");
INSERT INTO Category VALUES (743, "Taco", "Dishes");
INSERT INTO Category VALUES (744, "Soup", "Dishes");
INSERT INTO Category VALUES (745, "Fish & Chips", "Dishes");
INSERT INTO Category VALUES (746, "Bubble Tea", "Drinks");
INSERT INTO Category VALUES (747, "Boba", "Drinks");
INSERT INTO Category VALUES (748, "Pho", "Dishes");
INSERT INTO Category VALUES (749, "Pasta", "Dishes");
INSERT INTO Category VALUES (750, "Ramen", "Dishes");
INSERT INTO Category VALUES (751, "Shaved Ice", "Dishes");
INSERT INTO Category VALUES (752, "Smoothies", "Drinks");
INSERT INTO Category VALUES (753, "Steaks", "Dishes");
INSERT INTO Category VALUES (754, "Hot Pot", "Dishes");
INSERT INTO Category VALUES (755, "Tea", "Dishes");
INSERT INTO Category VALUES (756, "Noodles", "Dishes");
INSERT INTO Category VALUES (757, "Burritos", "Dishes");
INSERT INTO Category VALUES (758, "Cheesesteaks", "Dishes");
INSERT INTO Category VALUES (759, "Falafel", "Dishes");

INSERT INTO Category VALUES (760, "Fast Food", "Keywords");
INSERT INTO Category VALUES (761, "Healthy", "Keywords");
INSERT INTO Category VALUES (762, "Halal",  "Keywords");
INSERT INTO Category VALUES (763, "Breakfast", "Keywords");
INSERT INTO Category VALUES (764, "Desserts", "Keywords");
INSERT INTO Category VALUES (765, "Catering", "Keywords");
INSERT INTO Category VALUES (766, "Dinner", "Keywords");
INSERT INTO Category VALUES (767, "Grocery", "Keywords");
INSERT INTO Category VALUES (768, "Brunch", "Keywords");
INSERT INTO Category VALUES (769, "BBQ", "Keywords");
INSERT INTO Category VALUES (770, "Comfort Food", "Keywords");
INSERT INTO Category VALUES (771, "Vegan", "Keywords");
INSERT INTO Category VALUES (772, "Vegetarian", "Keywords");
INSERT INTO Category VALUES (773, "Gluten-Free", "Keywords");
INSERT INTO Category VALUES (774, "Poke", "Keywords");
INSERT INTO Category VALUES (775, "Bar and Grill",  "Keywords");
INSERT INTO Category VALUES (776, "Ethnic Food", "Keywords");
INSERT INTO Category VALUES (777, "Family Meals", "Keywords");
INSERT INTO Category VALUES (778, "Sweets", "Keywords");
INSERT INTO Category VALUES (779, "Late Night", "Keywords");
INSERT INTO Category VALUES (780, "Kids Meals", "Keywords");
INSERT INTO Category VALUES (781, "Buffets", "Keywords");
INSERT INTO Category VALUES (782, "Seafood", "Keywords");
INSERT INTO Category VALUES (783, "Beverages", "Keywords");
INSERT INTO Category VALUES (784, "Tex-Mex", "Keywords");
INSERT INTO Category VALUES (785, "Street Food", "Keywords");
INSERT INTO Category VALUES (786, "Alcohol",  "Keywords");
INSERT INTO Category VALUES (787, "Pubs", "Keywords");
INSERT INTO Category VALUES (788, "Deli", "Keywords");
INSERT INTO Category VALUES (789, "Sports Bar", "Keywords");
INSERT INTO Category VALUES (790, "Nutrition", "Keywords");
INSERT INTO Category VALUES (791, "Shakes", "Keywords");
INSERT INTO Category VALUES (792, "Cajun", "Keywords");
INSERT INTO Category VALUES (793, "Hakka", "Keywords");