INSERT INTO Promotion VALUES (501, "30% off $50 minimum order", "Monthly");
INSERT INTO Promotion VALUES (502, "10% off $100 minimum order", "Monthly");
INSERT INTO Promotion VALUES (503, "30% off $75 minimum order", "Monthly");
INSERT INTO Promotion VALUES (504, "up to 10% off any order", "Holiday/Special Ocassion");
INSERT INTO Promotion VALUES (505, "up to 20% off any order", "Holiday/Special Ocassion");
INSERT INTO Promotion VALUES (506, "up to 30% off any order", "Holiday/Special Ocassion");
INSERT INTO Promotion VALUES (507, "20% off first meal", "Restaurants are Newly Added");
INSERT INTO Promotion VALUES (508, "FREE delivery first meal", "Individual Restaurants promotion");
INSERT INTO Promotion VALUES (509, "FREE delivery on order more than $15", "Individual Restaurants promotion");
INSERT INTO Promotion VALUES (510, "FREE delivery on order more than $20", "Individual Restaurants promotion");
INSERT INTO Promotion VALUES (511, "FREE delivery on order more than $35", "Individual Restaurants promotion");
INSERT INTO Promotion VALUES (512, "FREE delivery", "Random Happy Hour");
INSERT INTO Promotion VALUES (513, "10% off any order", "Random Happy Hour");
INSERT INTO Promotion VALUES (514, "15% off any order", "Random Happy Hour");
INSERT INTO Promotion VALUES (515, "20% off any order", "Random Happy Hour");
INSERT INTO Promotion VALUES (516, "30% off any order", "Random Happy Hour");
INSERT INTO Promotion VALUES (517, "40% off any order", "Random Happy Hour");
INSERT INTO Promotion VALUES (518, "Automatic FREE delivery", "DashPass subscription");
INSERT INTO Promotion VALUES (519, "Up to 10% off", "Refer to a friend");